import { BlogPost } from "@/components/BlogCard";
import { getRandomContent } from "./blogPostContent";

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "topic-of-blog-post-ai-and-the-future-of-business",
    title: "Topic of Blog Post: AI and the Future of Business",
    excerpt:
      "Discover how artificial intelligence is revolutionizing business operations and creating new opportunities for growth.",
    category: "BLOG CATEGORY",
    date: "June 24, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-1.png",
    featured: true,
    bgColor: "#9B87F5",
    readTime: "5 min read",
    content: getRandomContent(),
  },
  {
    id: "2",
    slug: "is-ai-going-to-take-your-marketing-job",
    title: "Is AI Going to Take Your Marketing Job?",
    category: "BLOG CATEGORY",
    date: "June 20, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-2.png",
    bgColor: "#14B8A6",
    readTime: "4 min read",
    content: getRandomContent(),
  },
  {
    id: "3",
    slug: "what-happens-after-lead-generation",
    title: "What happens after lead generation?",
    category: "BLOG CATEGORY",
    date: "June 18, 2025",
    author: "Torq Team",
    image: "/icons/Blog-image.png",
    bgColor: "#D5FC9A",
    readTime: "6 min read",
    content: getRandomContent(),
  },
  {
    id: "4",
    slug: "how-to-optimize-your-sales-funnel-with-ai",
    title: "How to Optimize Your Sales Funnel with AI",
    category: "AI TECHNOLOGY",
    date: "June 15, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-1.png",
    bgColor: "#9B87F5",
    readTime: "7 min read",
    content: getRandomContent(),
  },
  {
    id: "5",
    slug: "the-ultimate-guide-to-marketing-automation",
    title: "The Ultimate Guide to Marketing Automation",
    category: "MARKETING + SALES",
    date: "June 12, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-2.png",
    bgColor: "#14B8A6",
    readTime: "8 min read",
    content: getRandomContent(),
  },
  {
    id: "6",
    slug: "understanding-customer-behavior-with-data-analytics",
    title: "Understanding Customer Behavior with Data Analytics",
    category: "AI TECHNOLOGY",
    date: "June 10, 2025",
    author: "Torq Team",
    image: "/icons/Blog-image.png",
    bgColor: "#D5FC9A",
    readTime: "6 min read",
    content: getRandomContent(),
  },
  {
    id: "7",
    slug: "5-ways-ai-can-transform-your-content-strategy",
    title: "5 Ways AI Can Transform Your Content Strategy",
    category: "MARKETING + SALES",
    date: "June 8, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-1.png",
    bgColor: "#9B87F5",
    readTime: "5 min read",
    content: getRandomContent(),
  },
  {
    id: "8",
    slug: "building-a-scalable-lead-generation-system",
    title: "Building a Scalable Lead Generation System",
    category: "MARKETING + SALES",
    date: "June 5, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-2.png",
    bgColor: "#14B8A6",
    readTime: "7 min read",
    content: getRandomContent(),
  },
  {
    id: "9",
    slug: "the-role-of-ai-in-modern-customer-service",
    title: "The Role of AI in Modern Customer Service",
    category: "AI TECHNOLOGY",
    date: "June 3, 2025",
    author: "Torq Team",
    image: "/icons/Blog-image.png",
    bgColor: "#D5FC9A",
    readTime: "6 min read",
    content: getRandomContent(),
  },
  {
    id: "10",
    slug: "announcing-torq-2-0-next-generation-platform",
    title: "Announcing Torq 2.0: Next Generation Platform",
    category: "COMPANY NEWS",
    date: "June 1, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-1.png",
    bgColor: "#9B87F5",
    readTime: "4 min read",
    content: getRandomContent(),
  },
  {
    id: "11",
    slug: "how-to-measure-roi-on-your-marketing-campaigns",
    title: "How to Measure ROI on Your Marketing Campaigns",
    category: "MARKETING + SALES",
    date: "May 28, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-2.png",
    bgColor: "#14B8A6",
    readTime: "6 min read",
    content: getRandomContent(),
  },
  {
    id: "12",
    slug: "ai-powered-insights-for-better-decision-making",
    title: "AI-Powered Insights for Better Decision Making",
    category: "AI TECHNOLOGY",
    date: "May 25, 2025",
    author: "Torq Team",
    image: "/icons/Blog-image.png",
    bgColor: "#D5FC9A",
    readTime: "7 min read",
    content: getRandomContent(),
  },
  {
    id: "13",
    slug: "industry-trends-the-future-of-b2b-marketing",
    title: "Industry Trends: The Future of B2B Marketing",
    category: "INDUSTRY RESOURCES",
    date: "May 22, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-1.png",
    bgColor: "#9B87F5",
    readTime: "8 min read",
    content: getRandomContent(),
  },
  {
    id: "14",
    slug: "case-study-increasing-conversion-rates-by-300",
    title: "Case Study: Increasing Conversion Rates by 300%",
    category: "MARKETING + SALES",
    date: "May 20, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-2.png",
    bgColor: "#14B8A6",
    readTime: "5 min read",
    content: getRandomContent(),
  },
  {
    id: "15",
    slug: "best-practices-for-email-marketing-in-2025",
    title: "Best Practices for Email Marketing in 2025",
    category: "INDUSTRY RESOURCES",
    date: "May 18, 2025",
    author: "Torq Team",
    image: "/icons/Blog-image.png",
    bgColor: "#D5FC9A",
    readTime: "7 min read",
    content: getRandomContent(),
  },
  {
    id: "16",
    slug: "the-power-of-personalization-in-sales-outreach",
    title: "The Power of Personalization in Sales Outreach",
    category: "MARKETING + SALES",
    date: "May 15, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-1.png",
    bgColor: "#9B87F5",
    readTime: "6 min read",
    content: getRandomContent(),
  },
  {
    id: "17",
    slug: "torq-wins-best-ai-platform-award-2025",
    title: "Torq Wins Best AI Platform Award 2025",
    category: "COMPANY NEWS",
    date: "May 12, 2025",
    author: "Torq Team",
    image: "/icons/blog-image-2.png",
    bgColor: "#14B8A6",
    readTime: "3 min read",
    content: getRandomContent(),
  },
  {
    id: "18",
    slug: "understanding-machine-learning-for-business-leaders",
    title: "Understanding Machine Learning for Business Leaders",
    category: "AI TECHNOLOGY",
    date: "May 10, 2025",
    author: "Torq Team",
    image: "/icons/Blog-image.png",
    bgColor: "#D5FC9A",
    readTime: "9 min read",
    content: getRandomContent(),
  },
];
